// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4SUqAfTuOU67fvgCxkCGDBHH0-kveblA',
    appId: '1:610879933772:web:ace2c5ba463b8f573953e9',
    messagingSenderId: '610879933772',
    projectId: 'birds-app-6e68c',
    authDomain: 'birds-app-6e68c.firebaseapp.com',
    databaseURL: 'https://birds-app-6e68c-default-rtdb.firebaseio.com',
    storageBucket: 'birds-app-6e68c.appspot.com',
    measurementId: 'G-S1GD0HVP8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3b46QENyMUxxndgOthsGfhufJ9QASfv8',
    appId: '1:610879933772:android:850943912b3c94e33953e9',
    messagingSenderId: '610879933772',
    projectId: 'birds-app-6e68c',
    databaseURL: 'https://birds-app-6e68c-default-rtdb.firebaseio.com',
    storageBucket: 'birds-app-6e68c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnmDBvizqgjn0hyg01wsQvdv14D6cnSl8',
    appId: '1:610879933772:ios:7a4839c07d60a0303953e9',
    messagingSenderId: '610879933772',
    projectId: 'birds-app-6e68c',
    databaseURL: 'https://birds-app-6e68c-default-rtdb.firebaseio.com',
    storageBucket: 'birds-app-6e68c.appspot.com',
    iosClientId: '610879933772-jfj7qeo0st5cu7h8bf6qsl3ka5qq6i5e.apps.googleusercontent.com',
    iosBundleId: 'com.example.birdzApp',
  );
}
